language: node_js
node_js:
  - 18
cache:
  directories:
  - node_modules
before_install:
  - echo "Script before to install";
install:
  - bundle install --path vendor/bundle
  - npm install --prefix app