language: node_js
node_js:
  - 20
cache:
  directories:
  - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - bundle install --path vendor/bundle
  - yarn install --modules-folder app