name: rust-postgres
services:
  db:
    container_name: db
    image: postgres:12-alpine
    restart: always
    hostname: db
    environment:
      - POSTGRES_USER=poli
      - POSTGRES_PASSWORD=poli453
      - POSTGRES_HOST=db
    networks:
      - server-side
    ports:
      - 5420:5432
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql
  backend:
    container_name: backend
    image: francescoxx/rustapp:1.0.0
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - server-side
  jenkis:
    container_name: jenkins
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  server-side: {}