apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - uses: docker://node:10-alpine
        name: Say hello
        run: ls
